ResourcePlanner/Models/EntityListView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ResourcePlanner.Models
{
    public class EntityListView
    {
        public enum EntityType{
            Person,
            Project
        }
        public EntityType Type { get; set; }
        public string URL { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

ResourcePlanner/Controllers/MSUSController.cs
using ResourcePlanner.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ResourcePlanner.Controllers
{
    public class MSUSController : Controller
    {
        private UsersContext db = new UsersContext();
        // GET: MSUS
        public ActionResult Index(string searchString)
        {
            return View(db.Persons.OrderBy(p => p.Name).ToList());
        }

        // GET: MSUS/Autocomplete
        public ActionResult Autocomplete(string term)
        {
            string[] people = db.Persons.Select(p => p.Name.ToUpper()).ToArray();
            return this.Json(people.Where(p => p.StartsWith(term.ToUpper())), JsonRequestBehavior.AllowGet);
        }

        // GET: MSUS/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MSUS/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MSUS/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MSUS/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MSUS/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MSUS/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MSUS/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ResourcePlanner/Views/MSUS/Index.cshtml
@model IEnumerable<ResourcePlanner.Models.Person>
@{
    ViewBag.Title = "Index";
    Layout = null;
}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>MC Planner</title>
        <script src="~/Scripts/bootstrap.min.js"></script>
        @Styles.Render("~/Content/themes/base/css")
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
        <link rel="stylesheet" href="~/Content/themes/bootstrap/bootstrap.min.css">
    </head>
<body>
    <div class="container">
        <div class="row" style="vertical-align:top; padding-bottom:10px">
            <div class="col-md-2" style="vertical-align:top;">
                <a href="@Url.Action("Index")">
                    <img src="http://upload.uxpin.s3.amazonaws.com/files/108665/115714/create_logo.png"
                         title="Logo" alt="Home" />
                </a>
            </div>
            <div class="col-md-2" style="vertical-align:bottom;">
                <h1>Planner</h1>
            </div>
            <div class="col-md-4 hidden-xs">
                <a class="btn btn-default" href="#">Add a Project +</a>
            </div>
            <div class="col-md-3 hidden-xs">
                <a class="btn btn-default" href="#">Day</a>
                <a class="btn btn-default active" href="#">Week</a>
                @*<a class="btn btn-default" href="#">Month</a>*@
            </div>
            <div class="col-md-1 hidden-xs">
                <a class="glyphicon glyphicon-cog" href="#" style="font-size:xx-large"></a>
            </div>
        </div>
        <div class="row">
            <div>
                <div class="col-md-4" style="background-color:white; height:20%;">
                    <form class=" form-inline" role="form">
                        <div class="form-group" style="background-color:gray; padding:2em;">
                            <div class="input-group">
                                @*<label for="txtSearch">Tags: </label>*@
                                <input type="text" class="form-control" id="txtSearch" placeholder="Search people or projects">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button">Search</button>
                                </span>
                            </div>
                        </div>
                       @Html.Partial("_EntityListView", Model)
                        <div style="height:1%;"></div>
                        <div style="background-color:lightgray; padding:1em;">
                            <div><a href="#" class="glyphicon glyphicon-plus-sign"></a></div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-8">
                rergreg rgregreg egq
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">

            </div>
        </div>
    </div>
    <script type="text/javascript">

    $(function () {
        $('#txtSearch').autocomplete({
            source: function (request, response) {

                $.ajax({
                    url: '@Url.Action("AutoComplete", "MSUS")',
                    dataType: "json",
                    contentType: 'application/json, charset=utf-8',
                    data: {
                        term: $("#txtSearch").val()
                    },
                    success: function (data) {

                        response($.map(data, function (item) {
                            return {
                                label: item
                            };
                        }));
                    },
                    error: function (xhr, status, error) {
                        alert(error);
                    }
                });
            },
            minLength: 2
        });
    });
 
    </script>
</body>
</html>

ResourcePlanner/Views/MSUS/_EntityListView.cshtml
@model IEnumerable<ResourcePlanner.Models.Person>

@foreach (var entity in Model)
{
    <div style="height:1%;"></div>
    <div style="background-color:darkslategray; padding:1em;">
        <div style="color:white;"><h3>@entity.Name</h3></div>
        <div style="color:white;">@entity.Role.Name</div>
    </div>
}